In [ ]:
#Exercice 1

import numpy as np

arr = np.arange(10)
print(arr)
# Output: array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Exercice 2

import numpy as np

lst = [3.14, 2.17, 0, 1, 2]
arr = np.array(lst).astype(int)
print(arr)
# Output: array([3, 2, 0, 1, 2])

In [ ]:
#Exercice 3

import numpy as np

arr = np.arange(1, 10).reshape(3, 3)
print(arr)
# Output: 
# array([[1, 2, 3],
#        [4, 5, 6],
#        [7, 8, 9]])

In [ ]:
#Exercice 4

import numpy as np

arr = np.random.rand(4, 5).round(2)  # round to 2 decimal places for cleaner output
print(arr)
# Output similar to:
# array([[0.56, 0.85, 0.01, 0.42, 0.68],
#        [0.22, 0.37, 0.73, 0.93, 0.39],
#        [0.44, 0.03, 0.87, 0.02, 0.83],
#        [0.78, 0.87, 0.98, 0.80, 0.46]])

In [ ]:
#Exercice 5

import numpy as np

array = np.array([[21,22,23,22,22], [20,21,22,23,24], [21,22,23,22,22]])
second_row = array[1]  # Index 1 is the second row
print(second_row)
# Output: array([20, 21, 22, 23, 24])

In [ ]:
#Exercice 6

import numpy as np

arr = np.arange(10)
reversed_arr = arr[::-1]
print(reversed_arr)
# Output: array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
#Exercice 7

import numpy as np

identity_matrix = np.eye(4)
print(identity_matrix)
# Output:
# array([[1., 0., 0., 0.],
#        [0., 1., 0., 0.],
#        [0., 0., 1., 0.],
#        [0., 0., 0., 1.]])

In [ ]:
#Exercice 8

import numpy as np

arr = np.arange(10)
total = np.sum(arr)
average = np.mean(arr)
print(f"Sum: {total}, Average: {average}")
# Output: Sum: 45, Average: 4.5

In [ ]:
#Exercice 9

import numpy as np

arr = np.arange(1, 21)
reshaped_arr = arr.reshape(4, 5)
print(reshaped_arr)
# Output:
# array([[ 1,  2,  3,  4,  5],
#        [ 6,  7,  8,  9, 10],
#        [11, 12, 13, 14, 15],
#        [16, 17, 18, 19, 20]])

In [ ]:
#Exercice 10

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
odd_numbers = arr[arr % 2 == 1]
print(odd_numbers)
# Output: array([1, 3, 5, 7, 9])