In [3]:
#Exersercice 1

import numpy as np

# Création d'une matrice 3x3
A = np.array([
    [2, 1, 3],
    [0, 4, 1],
    [5, 2, 8]
])

print("=" * 40)
print("       OPÉRATIONS MATRICIELLES")
print("=" * 40)

print("\n Matrice A :")
print(A)

# 1. Calcul du déterminant
det = np.linalg.det(A)
print(f"\n1️  Déterminant de A : {det:.4f}")

# Vérification si la matrice est inversible
if abs(det) < 1e-10:
    print("  La matrice n'est pas inversible (déterminant ≈ 0).")
else:
    print(" La matrice est inversible (déterminant ≠ 0).")

    # 2. Calcul de l'inverse
    A_inv = np.linalg.inv(A)
    print("\n2️  Inverse de A :")
    print(np.round(A_inv, 4))

    # Vérification : A * A_inv doit donner la matrice identité
    identite = np.round(A @ A_inv, 10)
    print("\n Vérification — A × A⁻¹ (doit être la matrice identité) :")
    print(identite)

print("=" * 40)

       OPÉRATIONS MATRICIELLES

 Matrice A :
[[2 1 3]
 [0 4 1]
 [5 2 8]]

1️  Déterminant de A : 5.0000
 La matrice est inversible (déterminant ≠ 0).

2️  Inverse de A :
[[ 6.  -0.4 -2.2]
 [ 1.   0.2 -0.4]
 [-4.   0.2  1.6]]

 Vérification — A × A⁻¹ (doit être la matrice identité) :
[[ 1.  0. -0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [4]:
# Exercice 2

# Fixer la graine pour la reproductibilité
np.random.seed(42)

# Génération de 50 nombres aléatoires (entre 0 et 100)
donnees = np.random.randint(0, 100, size=50)

print("=" * 45)
print("         ANALYSE STATISTIQUE")
print("=" * 45)

print(f"\n Tableau de 50 nombres aléatoires :")
print(donnees)

# 1. Moyenne et Médiane
moyenne = np.mean(donnees)
mediane = np.median(donnees)

print(f"\n1️  Moyenne  : {moyenne:.2f}")
print(f"    Médiane  : {mediane:.2f}")

# 2. Écart type
ecart_type = np.std(donnees)

print(f"\n2️  Écart type : {ecart_type:.2f}")

# Informations supplémentaires utiles
print(f"\n Infos complémentaires :")
print(f"    Valeur minimale : {np.min(donnees)}")
print(f"    Valeur maximale : {np.max(donnees)}")
print(f"    Étendue         : {np.max(donnees) - np.min(donnees)}")

print("=" * 45)

         ANALYSE STATISTIQUE

 Tableau de 50 nombres aléatoires :
[51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37  1 63 59 20
 32 75 57 21 88 48 90 58 41 91 59 79 14 61 61 46 61 50 54 63  2 50  6 20
 72 38]

1️  Moyenne  : 50.84
    Médiane  : 55.50

2️  Écart type : 27.85

 Infos complémentaires :
    Valeur minimale : 1
    Valeur maximale : 99
    Étendue         : 98


In [ ]:
# Exercice 3

print("=" * 45)
print("        MANIPULATION DE DATES")
print("=" * 45)
 
# Création du tableau de dates pour janvier 2023
dates_janvier = np.arange('2023-01-01', '2023-02-01', dtype='datetime64[D]')
 
print(f"\n Dates de janvier 2023 (format par défaut AAAA-MM-JJ) :")
print(dates_janvier)
 
# Conversion au format AAAA/MM/JJ
print(f"\n Dates converties au format AAAA/MM/JJ :")
dates_converties = np.array([str(date).replace('-', '/') for date in dates_janvier])
print(dates_converties)
 
# Informations supplémentaires
print(f"\n Informations :")
print(f"    Nombre de jours  : {len(dates_janvier)}")
print(f"    Première date    : {dates_converties[0]}")
print(f"    Dernière date    : {dates_converties[-1]}")
 
print("=" * 45)

In [ ]:
# EXERCICE 4

import pandas as pd
 
np.random.seed(42)
 
# Création du DataFrame avec des nombres aléatoires
df = pd.DataFrame(
    np.random.randint(10, 100, size=(6, 4)),
    columns=['Maths', 'Physique', 'Chimie', 'Biologie'],
    index=[f'Élève {i+1}' for i in range(6)]
)
 
print("=" * 55)
print("       MANIPULATION DE DONNÉES — PANDAS")
print("=" * 55)
 
print("\n DataFrame original (notes sur 100) :")
print(df)
 
# ─────────────────────────────────────────
# 1. SÉLECTION CONDITIONNELLE
# ─────────────────────────────────────────
print("\n" + "─" * 55)
print("1️  SÉLECTION CONDITIONNELLE")
print("─" * 55)
 
# a) Notes supérieures à 70 (True/False)
print("\n a) Notes supérieures à 70 (masque booléen) :")
print(df > 70)
 
# b) Lignes où la moyenne est >= 60
df['Moyenne'] = df.mean(axis=1).round(2)
bons_eleves = df[df['Moyenne'] >= 60]
print("\n b) Élèves avec une moyenne >= 60 :")
print(bons_eleves)
 
# c) Élèves ayant eu >= 70 en Maths
print("\n c) Élèves avec note >= 70 en Maths :")
print(df[df['Maths'] >= 70][['Maths', 'Moyenne']])
 
# ─────────────────────────────────────────
# 2. FONCTIONS D'AGRÉGATION
# ─────────────────────────────────────────
print("\n" + "─" * 55)
print("2️  FONCTIONS D'AGRÉGATION (sans colonne Moyenne)")
print("─" * 55)
 
notes = df.drop(columns='Moyenne')
 
print(f"\n Somme par matière :")
print(notes.sum())
 
print(f"\n Moyenne par matière :")
print(notes.mean().round(2))
 
print(f"\n Résumé complet :")
print(notes.describe().round(2))
 
print("=" * 55)

In [ ]:
# Exercice 5
import numpy as np

# Image 5x5 en niveaux de gris
# 0 = noir, 255 = blanc
image = np.array([
    [  0,  50, 100, 150, 200],
    [ 50, 100, 150, 200, 255],
    [100, 150, 200, 255, 200],
    [150, 200, 255, 200, 150],
    [200, 255, 200, 150, 100]
], dtype=np.uint8)

print("📷 Image 5x5 en niveaux de gris :")
print(image)

print(f"\nForme  : {image.shape}   → (lignes, colonnes)")
print(f"Type   : {image.dtype}  → valeurs entre 0 et 255")
print(f"Min    : {image.min()}   → pixel le plus sombre")
print(f"Max    : {image.max()}  → pixel le plus clair")

# Accéder à un pixel précis
print(f"\nPixel à la position [0,0] : {image[0, 0]}  (noir)")
print(f"Pixel à la position [1,4] : {image[1, 4]}  (blanc)")

In [5]:
#EXERCICE 6 

np.random.seed(42)

# Données fournies
productivity_before = np.random.normal(loc=50, scale=10, size=30)
productivity_after  = productivity_before + np.random.normal(loc=5, scale=3, size=30)

print("=" * 52)
print("        TEST D'HYPOTHÈSES — NUMPY")
print("=" * 52)

# ─────────────────────────────────────────
# FORMULATION DE L'HYPOTHÈSE
# ─────────────────────────────────────────
print("""
 Hypothèses :
   H0 (nulle)      : La formation n'a aucun effet
                     → moyenne de la différence = 0
   H1 (alternative): La formation améliore la productivité
                     → moyenne de la différence > 0
""")

# ─────────────────────────────────────────
# STATISTIQUES DESCRIPTIVES
# ─────────────────────────────────────────
print("─" * 52)
print("1️  STATISTIQUES DESCRIPTIVES")
print("─" * 52)
print(f"  Moyenne avant  : {np.mean(productivity_before):.2f}")
print(f"  Moyenne après  : {np.mean(productivity_after):.2f}")

differences = productivity_after - productivity_before
print(f"\n  Différence moyenne       : {np.mean(differences):.2f}")
print(f"  Écart type des différences: {np.std(differences):.2f}")

# ─────────────────────────────────────────
# TEST MANUEL (t-test apparié simplifié)
# ─────────────────────────────────────────
print("\n" + "─" * 52)
print("2️  CALCUL DE LA STATISTIQUE t")
print("─" * 52)

n           = len(differences)
moy_diff    = np.mean(differences)
std_diff    = np.std(differences, ddof=1)   # ddof=1 → écart type de l'échantillon
erreur_std  = std_diff / np.sqrt(n)
t_stat      = moy_diff / erreur_std

print(f"  Taille échantillon (n) : {n}")
print(f"  Moyenne des différences: {moy_diff:.2f}")
print(f"  Écart type             : {std_diff:.2f}")
print(f"  Erreur standard        : {erreur_std:.4f}")
print(f"  Statistique t calculée : {t_stat:.4f}")

# ─────────────────────────────────────────
# DÉCISION (seuil t critique ≈ 1.699 pour n=30, α=0.05)
# ─────────────────────────────────────────
print("\n" + "─" * 52)
print("3️  DÉCISION")
print("─" * 52)

t_critique = 1.699   # valeur standard pour n=30, α=0.05 unilatéral

print(f"  Valeur t calculée : {t_stat:.4f}")
print(f"  Valeur t critique : {t_critique} (seuil α = 0.05)")

if t_stat > t_critique:
    print("\n   t > t_critique → On REJETTE H0")
    print("  → La formation améliore significativement la productivité.")
else:
    print("\n   t ≤ t_critique → On NE REJETTE PAS H0")
    print("  → Pas de preuve suffisante d'amélioration.")

print("=" * 52)

        TEST D'HYPOTHÈSES — NUMPY

 Hypothèses :
   H0 (nulle)      : La formation n'a aucun effet
                     → moyenne de la différence = 0
   H1 (alternative): La formation améliore la productivité
                     → moyenne de la différence > 0

────────────────────────────────────────────────────
1️  STATISTIQUES DESCRIPTIVES
────────────────────────────────────────────────────
  Moyenne avant  : 48.12
  Moyenne après  : 52.76

  Différence moyenne       : 4.64
  Écart type des différences: 2.75

────────────────────────────────────────────────────
2️  CALCUL DE LA STATISTIQUE t
────────────────────────────────────────────────────
  Taille échantillon (n) : 30
  Moyenne des différences: 4.64
  Écart type             : 2.79
  Erreur standard        : 0.5100
  Statistique t calculée : 9.0915

────────────────────────────────────────────────────
3️  DÉCISION
────────────────────────────────────────────────────
  Valeur t calculée : 9.0915
  Valeur t critique : 1.699 (seu

In [ ]:
#Exercice 7

np.random.seed(42)
 
# Création des deux tableaux
A = np.random.randint(1, 20, size=(4, 4))
B = np.random.randint(1, 20, size=(4, 4))
 
print("=" * 45)
print("    COMPARAISON DE TABLEAUX — NUMPY")
print("=" * 45)
 
print("\n📋 Tableau A :")
print(A)
 
print("\n📋 Tableau B :")
print(B)
 
# Comparaison élément par élément
comparaison = A > B
 
print("\n🔍 A > B (tableau booléen) :")
print(comparaison)
 
# Informations supplémentaires
print(f"\n📌 Résumé :")
print(f"  Éléments où A > B : {np.sum(comparaison)}")
print(f"  Éléments où A ≤ B : {np.sum(~comparaison)}")
 
# Valeurs de A qui sont supérieures à B
print(f"\n✅ Valeurs de A supérieures à B :")
print(A[comparaison])
 
print("=" * 45)

In [ ]:

np.random.seed(42)

# Génération des données pour 2023
dates = pd.date_range(start='2023-01-01', end='2023-12-31', freq='D')
ventes = np.random.randint(100, 500, size=len(dates))
serie = pd.Series(ventes, index=dates)

print("=" * 48)
print("    SÉRIES TEMPORELLES 2023 — DÉCOUPAGE")
print("=" * 48)

trimestres = {
    "T1 — Janvier à Mars"   : ('2023-01-01', '2023-03-31'),
    "T2 — Avril à Juin"     : ('2023-04-01', '2023-06-30'),
    "T3 — Juillet à Sept."  : ('2023-07-01', '2023-09-30'),
    "T4 — Octobre à Déc."   : ('2023-10-01', '2023-12-31'),
}

for nom, (debut, fin) in trimestres.items():
    segment = serie[debut:fin]
    print(f"\n {nom}")
    print(f"   Jours     : {len(segment)}")
    print(f"   Moyenne   : {segment.mean():.1f}")
    print(f"   Min / Max : {segment.min()} / {segment.max()}")
    print(f"   5 premières valeurs : {segment.values[:5]}")

print("\n" + "=" * 48)

In [ ]:
# Esercice 9 

import numpy as np
import pandas as pd

np.random.seed(42)

print("=" * 48)
print("    CONVERSION NUMPY ↔ PANDAS")
print("=" * 48)

# ── NumPy → DataFrame ──────────────────────
tableau_numpy = np.random.randint(1, 100, size=(5, 3))

print("\n1️  Tableau NumPy original :")
print(tableau_numpy)
print(f"   Type : {type(tableau_numpy)}")

df = pd.DataFrame(tableau_numpy, columns=['A', 'B', 'C'])
print("\n Converti en DataFrame Pandas :")
print(df)
print(f"   Type : {type(df)}")

# ── DataFrame → NumPy ──────────────────────
retour_numpy = df.to_numpy()
print("\n2️  DataFrame reconverti en NumPy :")
print(retour_numpy)
print(f"   Type  : {type(retour_numpy)}")
print(f"   Forme : {retour_numpy.shape}")

print("=" * 48)

In [ ]:
#Exercice 10

import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)

# Données
x = np.arange(1, 51)
y = np.cumsum(np.random.randint(-5, 10, size=50))   # somme cumulée = tendance réaliste

fig, axes = plt.subplots(1, 3, figsize=(14, 4))
fig.suptitle("Visualisation de données NumPy", fontsize=13, fontweight='bold')

# Graphique 1 : Ligne
axes[0].plot(x, y, color='steelblue', linewidth=2)
axes[0].set_title("Graphique linéaire")
axes[0].set_xlabel("Observations")
axes[0].set_ylabel("Valeur cumulée")
axes[0].grid(True, linestyle='--', alpha=0.5)

# Graphique 2 : Barres
categories = ['Jan', 'Fév', 'Mar', 'Avr', 'Mai', 'Juin']
valeurs = np.random.randint(20, 100, size=6)
axes[1].bar(categories, valeurs, color='coral')
axes[1].set_title("Graphique en barres")
axes[1].set_ylabel("Ventes")

# Graphique 3 : Histogramme
donnees = np.random.normal(loc=60, scale=15, size=200)
axes[2].hist(donnees, bins=15, color='mediumseagreen', edgecolor='white')
axes[2].set_title("Histogramme")
axes[2].set_xlabel("Notes")
axes[2].set_ylabel("Fréquence")

plt.tight_layout()
plt.savefig('/mnt/user-data/outputs/exercice10_visualisation.png', dpi=120, bbox_inches='tight')
print("✅ Graphiques sauvegardés.")